ext	LINKK,NEST,SEMIS
public	TASK,INITDP

;                                                       +---------------------+
;                                                       !        TASK         !
;                                                       +---------------------+
	DB	84H
	DC	'TASK'
	DW	LINKK
TASK:	DW	NEST
	DW	SEMIS
;                                                 +---------------------------+
;                                                 !   Ende der Grundbefehle   !
;                                                 +---------------------------+
INITDP:	DB	0H
 
END
